FROM node:22-alpine AS deps
WORKDIR /usr/src/app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

FROM node:22-alpine AS build
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules COPY frontend/ ./
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /usr/src/app
ENV NODE_ENV=production
ENV PROTO_DIR=/usr/src/app/proto
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/next.config.js ./
COPY --from=build /usr/src/app/package.json ./
COPY proto/ ./proto
EXPOSE 8080
CMD ["npm", "run", "start"]
