// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: shipping.proto

package shipping

import (
	common "ecommerce/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         *common.Money          `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	EstimatedDays int32                  `protobuf:"varint,4,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingOption) Reset() {
	*x = ShippingOption{}
	mi := &file_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingOption) ProtoMessage() {}

func (x *ShippingOption) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingOption.ProtoReflect.Descriptor instead.
func (*ShippingOption) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingOption) GetPrice() *common.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ShippingOption) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *common.Address        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuoteRequest) GetAddress() *common.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*ShippingOption      `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteResponse) GetOptions() []*ShippingOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ShipOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Address       *common.Address        `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	OptionId      string                 `protobuf:"bytes,3,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderRequest) Reset() {
	*x = ShipOrderRequest{}
	mi := &file_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderRequest) ProtoMessage() {}

func (x *ShipOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderRequest.ProtoReflect.Descriptor instead.
func (*ShipOrderRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *ShipOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipOrderRequest) GetAddress() *common.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ShipOrderRequest) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

type ShipOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingId    string                 `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Carrier       string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderResponse) Reset() {
	*x = ShipOrderResponse{}
	mi := &file_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderResponse) ProtoMessage() {}

func (x *ShipOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderResponse.ProtoReflect.Descriptor instead.
func (*ShipOrderResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *ShipOrderResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *ShipOrderResponse) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

var File_shipping_proto protoreflect.FileDescriptor

const file_shipping_proto_rawDesc = "" +
	"\n" +
	"\x0eshipping.proto\x12\x12ecommerce.shipping\x1a\fcommon.proto\"\x8a\x01\n" +
	"\x0eShippingOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x05price\x18\x03 \x01(\v2\x17.ecommerce.common.MoneyR\x05price\x12%\n" +
	"\x0eestimated_days\x18\x04 \x01(\x05R\restimatedDays\"F\n" +
	"\x0fGetQuoteRequest\x123\n" +
	"\aaddress\x18\x01 \x01(\v2\x19.ecommerce.common.AddressR\aaddress\"P\n" +
	"\x10GetQuoteResponse\x12<\n" +
	"\aoptions\x18\x01 \x03(\v2\".ecommerce.shipping.ShippingOptionR\aoptions\"\x7f\n" +
	"\x10ShipOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x123\n" +
	"\aaddress\x18\x02 \x01(\v2\x19.ecommerce.common.AddressR\aaddress\x12\x1b\n" +
	"\toption_id\x18\x03 \x01(\tR\boptionId\"N\n" +
	"\x11ShipOrderResponse\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\tR\n" +
	"trackingId\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier2\xc2\x01\n" +
	"\x0fShippingService\x12U\n" +
	"\bGetQuote\x12#.ecommerce.shipping.GetQuoteRequest\x1a$.ecommerce.shipping.GetQuoteResponse\x12X\n" +
	"\tShipOrder\x12$.ecommerce.shipping.ShipOrderRequest\x1a%.ecommerce.shipping.ShipOrderResponseB\x14Z\x12ecommerce/shippingb\x06proto3"

var (
	file_shipping_proto_rawDescOnce sync.Once
	file_shipping_proto_rawDescData []byte
)

func file_shipping_proto_rawDescGZIP() []byte {
	file_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)))
	})
	return file_shipping_proto_rawDescData
}

var file_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shipping_proto_goTypes = []any{
	(*ShippingOption)(nil),    // 0: ecommerce.shipping.ShippingOption
	(*GetQuoteRequest)(nil),   // 1: ecommerce.shipping.GetQuoteRequest
	(*GetQuoteResponse)(nil),  // 2: ecommerce.shipping.GetQuoteResponse
	(*ShipOrderRequest)(nil),  // 3: ecommerce.shipping.ShipOrderRequest
	(*ShipOrderResponse)(nil), // 4: ecommerce.shipping.ShipOrderResponse
	(*common.Money)(nil),      // 5: ecommerce.common.Money
	(*common.Address)(nil),    // 6: ecommerce.common.Address
}
var file_shipping_proto_depIdxs = []int32{
	5, // 0: ecommerce.shipping.ShippingOption.price:type_name -> ecommerce.common.Money
	6, // 1: ecommerce.shipping.GetQuoteRequest.address:type_name -> ecommerce.common.Address
	0, // 2: ecommerce.shipping.GetQuoteResponse.options:type_name -> ecommerce.shipping.ShippingOption
	6, // 3: ecommerce.shipping.ShipOrderRequest.address:type_name -> ecommerce.common.Address
	1, // 4: ecommerce.shipping.ShippingService.GetQuote:input_type -> ecommerce.shipping.GetQuoteRequest
	3, // 5: ecommerce.shipping.ShippingService.ShipOrder:input_type -> ecommerce.shipping.ShipOrderRequest
	2, // 6: ecommerce.shipping.ShippingService.GetQuote:output_type -> ecommerce.shipping.GetQuoteResponse
	4, // 7: ecommerce.shipping.ShippingService.ShipOrder:output_type -> ecommerce.shipping.ShipOrderResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shipping_proto_init() }
func file_shipping_proto_init() {
	if File_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_proto_msgTypes,
	}.Build()
	File_shipping_proto = out.File
	file_shipping_proto_goTypes = nil
	file_shipping_proto_depIdxs = nil
}
