name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v6

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Test
        run: npm test

  Node-Services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          [authservice, cartservice, orderservice, paymentservice, emailservice]

    defaults:
      run:
        working-directory: ./services/${{ matrix.service  }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: services/${{ matrix.service }}

      - name: Install Dependencies
        run: npm  install

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          test_script=$(node -p "const s=require('./package.json').scripts||{}; s.test||''")
          if [ -n "$test_script" ]; then
            npm test
          else
            echo "No test script defined, skipping"
          fi

  Go-Services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service:
          [productservice, checkoutservice, shippingservice, promotionservice]

    defaults:
      run:
        working-directory: ./services/${{ matrix.service }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache: true

      - name: Build
        run: GOWORK=off go build -mod=vendor ./${{ matrix.service }}

      - name: Lint
        run: go vet .
      - name: Test
        run: go test .
